### ISSUE TITLE
Support the new Trackmania Game

### ISSUE THREAD

**Issue by oliverde8** [eXpansionPluginPack/eXpansion2#406]
Currently eXpansion² works with the new game, it can be used to administer the server. 

But various functionalities such as records don't work. This is due to the data providers not being compatible anymore

**TODO**
- [ ] Update title game mapping (src/eXpansion/Framework/Core/Resources/config/storage.yml)
- [ ] Create a new Framework/GameTrackmaniaNext bundle 
- [ ] Create the following new data providers: 
  - [ ] tm.script.waypoint (eXpansion\Framework\GameTrackmania\DataProviders\WayPointDataProvider)
  - [ ] tm.script.race (eXpansion\Framework\GameTrackmania\DataProviders\ScriptBaseRounds\RaceDataProvider) 
  - [ ] tm.script.race (eXpansion\Framework\GameTrackmania\DataProviders\ScriptTimeAttack\RaceDataProvider)
  - [ ] tm.script.lap (eXpansion\Framework\GameTrackmania\DataProviders\LapDataProvider) 
  - [ ] tm.script.player (eXpansion\Framework\GameTrackmania\DataProviders\PlayerEventsDataProvider)
  - [ ] mp.method.get_scores (eXpansion\Framework\GameTrackmania\DataProviders\MethodGetScoresDataProvider)
  - [ ] mp.method.get_number_lap (eXpansion\Framework\GameTrackmania\DataProviders\ScriptBaseRounds\MethodGetNumberLapsDataProvider && eXpansion\Framework\GameTrackmania\DataProviders\ScriptTimeAttack\MethodGetNumberLapsDataProvider)

Most cases the original classes can probably be reused with just different events to listen to. 

Some of the providers might not be possible to create in the new game, in which case plugins using those won't work.
